### ISSUE TITLE
Should write/write concern errors be converted to exceptions?

### ISSUE THREAD

**Issue by fehmicansaglam** [fehmicansaglam/tepkin#20]
Currently any write operation to MongoDB returns a `WriteResult`.  `ok: Boolean` member of this instance defines the success of the operation. One should explicitly check this value to understand if the operation succeeded or not.

I am thinking of converting the `ok=false` case to a corresponding exception. If the `ok` value is `false` then there will be `writeErrors` or a `writeConcernError` in the result. We can throw a `WriteException` or a `WriteConcernException` respectively.
## -A growing list of- Advantages
- Write errors are explicit and the execution is automatically stopped. So no silent/unnoticed failures.
- When write operations are composed using _Future composition_, next operation will not be run.
## -A growing list of- Disadvantages
-  When write operations are composed using _Future composition_, next operation will not be run. There may be some cases that the next operation should be run whether the current operation fails or not.

**Comment by malchmih** [comment]
As far as I see it, disadvantage about future composition is very rare and should be handled explicitly. So I'd choose exceptions. Also, by default, when I start using some new library, I expect it to throw exceptions (I mean, it's more intuitive).

**Comment by fehmicansaglam** [comment]
I agree @malchmih . I will wait for a couple of days for other comments.
