### ISSUE TITLE
add createCollection Command

### ISSUE THREAD

**Issue by danielwegener** [fehmicansaglam/tepkin#21]
Collections are usually create implicitly. But in some cases you might want to create a collection explicitly (or rather ensure that it exists). This is especially important for capped collections (they have to be declared _capped_ at creation). See also [mongo db.createCollection](http://docs.mongodb.org/manual/reference/method/db.createCollection/)
This might be useful for #13.

**Comment by danielwegener** [comment]
That was quick. Cheers @fehmicansaglam

**Comment by fehmicansaglam** [comment]
No problem.
