### ISSUE TITLE
Drop Java support

### ISSUE THREAD

**Issue by fehmicansaglam** [fehmicansaglam/tepkin#22]
As MongoDB is developing an official Reactive Streams driver for Java, I am planning to drop Java support in 0.6. What do you think?

http://mongodb.github.io/mongo-java-driver-reactivestreams/

**Comment by danielwegener** [comment]
:+1: Im fine with that.

**Comment by mushtaq** [comment]
Should be ok. Even though it in Java, it is minimal as it implements RS protocol. One expectation is that higher level libraries will wrap it. Have you though of pros/cons of tepkin as a wrapper around that?

**Comment by fehmicansaglam** [comment]
A wrapper around RxJava? I am not sure. It might be out of the scope of Tepkin. Currently tepkin-java is already a wrapper around tepkin. But it is really ugly to use/compose Futures in Java. This is one of the reasons why I want to drop Java support.

**Comment by mushtaq** [comment]
Oh, my bad. I assumed wrong destination for the link you gave! I thought you were referring to this one:

http://mongodb.github.io/mongo-java-driver-reactivestreams/
OR
https://github.com/mongodb/mongo-java-driver-reactivestreams

I did not know that there is yet another one based on RxJava. Does that one also implement RS?

**Comment by fehmicansaglam** [comment]
You are right. I am also confused, there are  too many reactive libraries. I was trying to refer to reactive streams java driver. RxJava should have a different api.

**Comment by mushtaq** [comment]
My question about wrapping was for the RS driver I linked. Will be good to know what you think.

**Comment by fehmicansaglam** [comment]
I don't like the idea of depending to another library even if it is an
official driver. Tepkin just depends on Akka. On the other hand wrapping
the official driver may result in a more stable library without worrying
about the updates to MongoDB. But honestly I like Tepkin to continue as it
is. I like working with Akka IO and Akka Streams. A wrapper for the RS
driver needs to be a different library/project.

**Comment by fehmicansaglam** [comment]
@mushtaq actually I just checked the RS driver's api and hated it. Even an insert/delete operation returns a Publisher and if I am not mistaken Publisher instances are not composable. I mean RS driver currently does not enable composing async operations. Right? If so I should reconsider dropping java support.

**Comment by mushtaq** [comment]
From their documentation (http://mongodb.github.io/mongo-java-driver-reactivestreams/1.0/getting-started/quick-tour-primer/): 

> In general Publishers, Subscribers and Subscriptions are a low level API and it’s expected that users and libraries will build more expressive APIs upon them rather than solely use these interfaces

Published/Subscriber interfaces are considered SPI and not expected to composable like a high level DSL. I expect users to do use it as shown here: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/scala/stream-integrations.html#Integrating_with_Reactive_Streams

> def tweets: Publisher[Tweet]
> def storage: Subscriber[Author]
> Source(tweets).via(authors).to(Sink(storage)).run()

Personally, I do not deal with Java, so quite ok for tepkin drop support.

**Comment by rozza** [comment]
Hi, just to clarify, the Reactive Streams Mongo Driver simply implements the Reactive Stream API and its use really is intended for connecting with other Reactive Stream libraries.  As mentioned above the Reactive Stream API is minimal and not necessarily the nicest API.  Only time will tell if the Reactive Streams project is ultimately successful, but I felt it was worth supporting its aims.  

As users want composable async operations, and because I'm a fan of [ReactiveX](http://reactivex.io/intro.html) and its excellent RxJava library we also decided to provide an Observer based API with the [Mongo RxJava driver](http://mongodb.github.io/mongo-java-driver-rx/).  For Java users this really is the most user friendly of the official MongoDB async drivers and because of that it is the one that I expect most users to adopt.  RxJava does allow you to control flow and supports [backpressure](https://github.com/ReactiveX/RxJava/wiki/Backpressure) and there's even a [Reactive Stream adapter](https://github.com/ReactiveX/RxJavaReactiveStreams) should you need it.

I'm not sure if that helps any with your decision!  I'm happy to answer any other questions if needed :)

**Comment by fehmicansaglam** [comment]
@rozza Thanks for your comment. I also like Reactive Streams and as you said there are adapters for converting between RxJava and Reactive Streams. At the time of the previous comments I didn't know that there was an easy way to convert one element Akka Stream Source(Publisher) to a Scala Future so it really didn't make sense to me to build Tepkin on top of your Reactive Streams Driver. But now it makes sense with Sink.head provided by Akka Stream. However I am not the one that will do it because I like writing code on top of Akka - it is just fun:)

As Java versions before 8 are too verbose I do not even support them. But even with Java 8 it is also difficult to compose CompletableFutures - possibly because of the lack of type inference. RxJava api is quite good but if I am not mistaken it does not support functional interfaces in Java 8 - again lots of boilerplate code.

Anyway, I decided to drop Java support. People can use those great libraries of yours:)

**Comment by rozza** [comment]
No worries @fehmicansaglam Akka sure is fun! :) 

Btw if you have any MongoDB related questions feel free to drop me a line.

**Comment by fehmicansaglam** [comment]
@rozza just one quick question. Do you have a mailing list for core developers where the upcoming features are discussed? If so is it public? That way I could start developing early for the new features. And maybe I could ask for some ideas on that list.

**Comment by rozza** [comment]
@fehmicansaglam I've sent you an email with the mailing lists and Jira projects to follow.
